---
pip_packages:
  - ansible
  - molecule
  - docker

# topics:
#   editor:
#     - name: vim
#       path: editor/vim
#       state: present
#       brew_formulas:
#         - vim
#     - name: emacs
#       path: editor/emacs
#       state: present
#       brew_taps:
#         - d12frosted/emacs-plus
#       brew_formulas:
#         - name: emacs_plus
#           install_options: without-spacemacs-icon
#   shell:
#     - name: zsh
#       path: shell/zsh
#       state: present
#       brew_formulas:
#         - zsh
#         - fzf
#         - ripgrep
#     - name: tmux
#       path: shell/tmux
#       state: present
#       brew_formulas:
#         - tmux

topics:
  base:
    - name: macos
      state: present
      config: "{{ macos_config }}"
  editor:
    - name: vim
      state: present
      config: "{{ vim_config }}"
    - name: emacs
      state: present
      config: "{{ emacs_config }}"
    - name: editorconfig
      state: present
      config: "{{ editorconfig_config }}"
  keyboard:
    - name: hammerspoon
      state: present
      config: "{{ hammerspoon_config }}"
    - name: karabiner
      state: present
      config: "{{ karabiner_config }}"
  shell:
    - name: alacritty
      state: present
      config: "{{ alacritty_config }}"
    - name: git
      state: present
      config: "{{ git_config }}"
    - name: tmux
      state: present
      config: "{{ tmux_config }}"
    - name: zsh
      state: present
      config: "{{ zsh_config }}"
  dev:
    - name: docker
      state: present
      config: "{{ docker_config }}"
  lang:
    - name: ruby
      state: present
      config: "{{ ruby_config }}"
    - name: java
      state: present
      config: "{{ java_config }}"
    - name: go
      state: present
      config: "{{ go_config }}"
