---
web_config:
  path: dev/web
  brew_formulas:
    - httpie
  pacman_packages:
    - httpie
  npm_packages:
    - firebase-tools
    - gatsby-cli
    - lorem-ipsum
    - netlify-cli
    - nodemon
    - npm-check-updates
    - prettier
    - serve
    - '@vue/cli'
