---
macos_config:
  path: base/macos
  brew_taps:
    - homebrew/cask-versions
    - homebrew/cask-fonts
  brew_casks:
    # essential
    - alfred
    - bartender
    - discord
    - dropbox
    - google-chrome
    - istat-menus
    - 1password
    - slack
    - spotify
    - textexpander
    - amethyst
    - balenaetcher
    # dev
    - firefox-developer-edition
    - postman
    # fonts
    - font-3270-nerd-font
    - font-dejavu-sans-mono-nerd-font
    - font-fira-code-nerd-font
    - font-hack-nerd-font
    - font-iosevka-nerd-font
    - font-mononoki-nerd-font
    - font-roboto-mono-nerd-font
    - font-source-code-pro
    - font-sauce-code-pro-nerd-font
  mas_apps:
    - id: 950297057
      name: "FuzzyTime"
    - id: 1435957248
      name: "Drafts"
    - id: 409183694
      name: "Keynote"
    - id: 441258766
      name: "Magnet"
    - id: 904280696
      name: "Things"
    - id: 1191449274
      name: "ToothFairy"
    - id: 1091189122
      name: "Bear"
    - id: 409201541
      name: "Pages"
    - id: 1176895641
      name: "Spark"
    - id: 409203825
      name: "Numbers"
  osx_defaults:
    - domain: com.apple.dock
      key: orientation
      value: left
      type: string
      state: present
    - domain: com.apple.dock
      key: autohide
      value: true
      type: boolean
      state: present
    - domain: com.apple.dock
      key: magnification
      value: true
      type: boolean
      state: present
    - domain: com.apple.dock
      key: largesize
      value: 44
      type: float
      state: present
